### ISSUE TITLE
Homwbrew SHA1 Deprecation Notice

### ISSUE THREAD

**Issue by rk** [michaeldfallen/homebrew-formula#5]
When updating homebrew installed packages, I got this. You'll need to push a patch soon:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!
```

**Comment by espinielli** [comment]
fix is about removing `sha1` line with the following

```
sha256 '27c9ebfe8470851099d3f4efe65370cf00c9b58d'
```

HTH

**Comment by eproxus** [comment]
@espinielli  Unfortunately breaks once `brew update` is run again.

**Comment by espinielli** [comment]
@eproxus there is a PR pending, #4, so it may soon be fixed...I needed to survive an upgrade on my machine...(I removed my comment here because I then discovered the PR...)

Also you can restate the temporary fix after `brew update` via (suggested by `brew` directly)

```
cd /usr/local/Library/Taps/michaeldfallen/homebrew-formula && git stash pop
```

HTH

**Comment by selfagency** [comment]
unfortunately the tap itself has the deprecation and @espinielli's fix above doesn't work

``` fish
» brew tap michaeldfallen/formula
==> Tapping michaeldfallen/formula
Cloning into '/usr/local/Library/Taps/michaeldfallen/homebrew-formula'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Tapped 2 formulae (27 files, 21.5K)
daniel at selfagecymacpro in ~
» cd /usr/local/Library/Taps/michaeldfallen/homebrew-formula & git stash pop
No stash found.
Job 1, 'cd /usr/local/Library/Taps/mich…' has ended
```

**Comment by mcphailtom** [comment]
Bumped the butler shasum as well to eliminate both tap errors https://github.com/michaeldfallen/homebrew-formula/pull/7

**Comment by michaeldfallen** [comment]
Both #7 and #6 merged. I'm on Ubuntu atm so wasn't looking at brew regularly. Sorry I missed this. Thanks everyone for addressing it for me.

Closing.
